"""Screenshot gallery page for Calamares (roadmap 5.6b lot 3, ADR-023).

Pure module. The QML view module `gluegallery` is static (hand-written); only
the data (GalleryData.js) and its modules/gluegallery.conf are generated from
the catalog, via calamares_config.render_all(). Data is embedded in a
`.pragma library` script because Qt blocks XMLHttpRequest reads of local files.
"""

from __future__ import annotations

import json
from typing import Dict, List, Sequence

FILE_URL_PREFIX = "file://"
_KINDS = (("gluesessions", "session"), ("glueshell", "shell"))
_HEADER_JS = ("// Generated by glue_installer.calamares_gallery from catalog.json;"
              " do not edit.\n// Regenerate: python -m glue_installer.calamares_config\n")
_HEADER_YAML = ("# Generated by glue_installer.calamares_gallery from catalog.json;"
                " do not edit.\n# Regenerate: python -m glue_installer.calamares_config\n")
DATA_PREFIX = ".pragma library\n\nvar entries = "


def build_gallery_entries(pages: Sequence) -> List[Dict[str, object]]:
    """Sessions first, then shells, in catalog order. Items without images are
    kept with images [] so the QML can show its fallback."""
    by_id = {p.id: p for p in pages}
    entries: List[Dict[str, object]] = []
    for page_id, kind in _KINDS:
        page = by_id.get(page_id)
        if page is None:
            raise ValueError(f"gallery needs page {page_id!r}")
        for item in page.items:
            if not item.id:      # the "Choose one or more" notice card
                continue
            entries.append({
                "id": item.id, "name": item.name, "kind": kind,
                "images": [FILE_URL_PREFIX + p for p in item.gallery
                           if p.startswith("/")],
            })
    return entries


def render_gallery_data_js(entries: Sequence[Dict[str, object]]) -> str:
    body = json.dumps(list(entries), indent=2, ensure_ascii=False)
    return _HEADER_JS + DATA_PREFIX + body + ";\n"


def parse_gallery_data_js(text: str) -> List[Dict[str, object]]:
    """Inverse of render_gallery_data_js (used by tests)."""
    start = text.index(DATA_PREFIX) + len(DATA_PREFIX)
    return json.loads(text[start:].rstrip().rstrip(";"))


def render_gallery_qml_conf() -> str:
    return (_HEADER_YAML + "---\nlabels:\n    step: \"Previews\"\n")
