"""Calamares sequence + Glue selection pages (roadmap 10.3 lot 2, ADR-023).

Pure module: no libcalamares, no filesystem access except main(). Everything
under packages/glue-calamares-config that depends on the catalog is GENERATED
from here (settings.conf and modules/glue*.conf); tests assert the committed
files equal the output byte for byte. One owner per operation: Calamares owns
partition/mount/fstab/locale/keyboard/users/umount, glueinstall owns packages,
Glue configuration, services and Limine, gluefstab owns the swapfile line.

Limit of packagechooser (method legacy): it writes ONE globalstorage key per
page, `packagechooser_<instance>` = comma-separated item ids, and cannot make a
page depend on another page's choice. The shell is therefore a separate page,
and selection_from_globalstorage() translates the page keys into the dict read
by calamares_adapter.parse_selection (no second catalog: ids come from it).
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Mapping, Optional

from glue_installer.ui_view import SESSIONS_NOTICE


class ConfigError(ValueError):
    """A globalstorage page value is not something the catalog offers."""


GS_PREFIX = "packagechooser_"
# Screenshots as installed by the glue-installer PKGBUILD (catalog paths are
# relative to the catalog directory).
SCREENSHOT_ROOT = "/usr/share/glue-installer/catalog"
NO_SCREENSHOT = ":/images/no-selection.png"
GAMING_ID_PREFIX = "gaming-"

# Calamares pages in the order the user sees them (instances of packagechooser).
PAGE_IDS = ("gluesessions", "glueshell", "gluekernel", "glueinit", "gluegaming",
            "glueextras")
SHOW_BEFORE = ("welcome", "locale", "keyboard", "partition", "users")
SHOW_AFTER = ("summary",)
# Standard fstab is kept (it knows UUIDs, options, crypttab, btrfs subvolumes
# and runs after basestrap so the `filesystem` package cannot conflict with an
# earlier /etc/fstab); gluefstab adds only the Glue swapfile line right after.
EXEC = ("partition", "mount", "glueinstall", "fstab", "gluefstab", "locale",
        "keyboard", "localecfg", "users", "umount")
SHOW_FINISH = ("finished",)
# Never in the sequence: bootloader/initramfs are glue-boot's, services and the
# greeter are config_steps', packages come from basestrap in glueinstall.
FORBIDDEN_MODULES = frozenset({
    "bootloader", "grubcfg", "initcpio", "initcpiocfg", "dracut", "mkinitfs",
    "services-systemd", "services-openrc", "shellprocess", "contextualprocess",
    "pacstrap", "chwd", "unpackfs", "unpackfsc", "packages", "netinstall",
    "displaymanager", "plymouthcfg",
})
_EXEC_COMMENTS = {
    "glueinstall": "basestrap + Glue config + Limine over the mounted root (10.3)",
    "fstab": "after basestrap: the filesystem package ships /etc/fstab",
    "gluefstab": "appends the Glue swapfile line recorded by glueinstall",
    "locale": "locale/keyboard/users after glueinstall: glibc, kbd, shells, groups",
    "users": "needs the target's passwd/group (video, audio, …) and /bin/bash",
}
_SETTINGS_FLAGS = (
    ("branding", "glue"), ("prompt-install", True), ("dont-chroot", False),
    ("oem-setup", False), ("disable-cancel", False),
    ("disable-cancel-during-exec", True), ("hide-back-and-next-during-exec", True),
    ("quit-at-end", False),
)
_HEADER = ("# Generated by glue_installer.calamares_config from catalog.json;"
           " do not edit.\n# Regenerate: python -m glue_installer.calamares_config\n")


@dataclass
class Item:
    id: str
    name: str
    description: str
    screenshot: str = NO_SCREENSHOT
    gallery: List[str] = field(default_factory=list)  # all images, absolute


@dataclass
class Page:
    id: str
    step: str
    mode: str                      # optional|required|optionalmultiple
    items: List[Item] = field(default_factory=list)
    default: Optional[str] = None  # pre-selected item id

    @property
    def gs_key(self) -> str:
        return GS_PREFIX + self.id

    def item_ids(self) -> List[str]:
        return [it.id for it in self.items if it.id]


# ---------------------------------------------------------------------------
# Pages from the catalog
# ---------------------------------------------------------------------------

def _shot(path: Optional[str]) -> str:
    return f"{SCREENSHOT_ROOT}/{path}" if path else NO_SCREENSHOT


def _item(entry, description: str) -> Item:
    shots = [_shot(p) for p in (entry.screenshots or ([entry.screenshot]
                                                      if entry.screenshot else []))]
    return Item(entry.id, entry.name, description, shots[0] if shots else NO_SCREENSHOT,
                shots)


def build_pages(catalog) -> List[Page]:
    """The six Glue pages, ids and texts taken from the catalog only."""
    sessions = Page("gluesessions", "Sessions", "optionalmultiple")
    sessions.items.append(Item("", "Choose one or more sessions", SESSIONS_NOTICE))
    for s in catalog.sessions:
        sessions.items.append(_item(s, s.description))
    sessions.default = "gluewc" if any(s.id == "gluewc" for s in catalog.sessions) \
        else catalog.sessions[0].id

    # Separate page: packagechooser cannot show it only when gluewc is ticked.
    shell = Page("glueshell", "Desktop shell", "required")
    for sh in catalog.shells:
        shell.items.append(_item(sh, sh.description + " Used by the gluewc session."))
    shell.default = "glueqs" if any(s.id == "glueqs" for s in catalog.shells) \
        else catalog.shells[0].id

    kernel = Page("gluekernel", "Kernel", "required")
    for k in catalog.kernels:
        kernel.items.append(Item(k.id, k.name, k.description))
    kernel.default = next((k.id for k in catalog.kernels if k.primary),
                          catalog.kernels[0].id)

    init = Page("glueinit", "Init system", "required")
    for i in catalog.inits:
        init.items.append(Item(i.id, i.name, i.description))
    init.default = next((i.id for i in catalog.inits if i.recommended),
                        catalog.inits[0].id)

    gaming = Page("gluegaming", "Gaming", "optional")
    gaming.items.append(Item(
        "", "No gaming stack",
        "Skip Steam, Proton, Wine and the gaming tweaks. You can add them later "
        "from Glue Apps."))
    for sched in catalog.gaming.schedulers:
        gaming.items.append(Item(
            GAMING_ID_PREFIX + sched.id, f"{catalog.gaming.name} ({sched.name})",
            f"{catalog.gaming.description} CPU scheduler: {sched.description}"))

    extras = Page("glueextras", "Extras", "optionalmultiple")
    for sup in catalog.support:
        extras.items.append(Item(sup.id, sup.name, sup.description))
    extras.default = next((s.id for s in catalog.support if s.default), None)
    pages = [sessions, shell, kernel, init, gaming, extras]
    assert tuple(p.id for p in pages) == PAGE_IDS
    return pages


def page_keys(catalog) -> List[str]:
    return [p.gs_key for p in build_pages(catalog)]


def has_page_values(gs: Mapping) -> bool:
    """True when at least one Glue page wrote its globalstorage key."""
    return any(k.startswith(GS_PREFIX + "glue") and gs.get(k) is not None for k in gs)


def _picked(gs: Mapping, page: Page) -> Optional[List[str]]:
    raw = gs.get(page.gs_key)
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise ConfigError(f"{page.gs_key} must be a string, got {type(raw).__name__}")
    ids = [tok.strip() for tok in raw.split(",") if tok.strip()]
    unknown = sorted(set(ids) - set(page.item_ids()))
    if unknown:
        raise ConfigError(f"{page.gs_key}: unknown choice(s) {unknown}")
    if page.mode == "required" and len(ids) != 1:
        raise ConfigError(f"{page.gs_key}: exactly one choice required, got {ids}")
    if page.mode == "optional" and len(ids) > 1:
        raise ConfigError(f"{page.gs_key}: at most one choice allowed, got {ids}")
    return ids


def selection_from_globalstorage(gs: Mapping, catalog) -> Dict[str, object]:
    """Translate the packagechooser keys into the parse_selection dict.
    Pages whose key is absent are left to parse_selection's defaults.
    Raises ConfigError (a ValueError) for ids outside the catalog."""
    pages = {p.id: p for p in build_pages(catalog)}
    sel: Dict[str, object] = {}
    sessions = _picked(gs, pages["gluesessions"])
    if sessions is not None:
        sel["sessions"] = sessions
    for page_id, key in (("glueshell", "shell"), ("gluekernel", "kernel"),
                         ("glueinit", "init")):
        ids = _picked(gs, pages[page_id])
        if ids:
            sel[key] = ids[0]
    gaming = _picked(gs, pages["gluegaming"])
    if gaming is not None:
        sel["gaming"] = bool(gaming)
        if gaming:
            sel["scheduler"] = gaming[0][len(GAMING_ID_PREFIX):]
    extras = _picked(gs, pages["glueextras"])
    if extras is not None:
        for sup in catalog.support:
            sel[sup.id.replace("-", "_")] = sup.id in extras
    return sel


# ---------------------------------------------------------------------------
# settings.conf
# ---------------------------------------------------------------------------

def build_settings(catalog) -> Dict[str, object]:
    pages = build_pages(catalog)
    show = list(SHOW_BEFORE) + [f"packagechooser@{p.id}" for p in pages] + list(SHOW_AFTER)
    settings: Dict[str, object] = {
        # `local` = /usr/lib/calamares/modules (system); the Glue job modules
        # (glueinstall, gluefstab) live under /etc/calamares/modules.
        "modules-search": ["local", "/etc/calamares/modules"],
        "instances": [{"id": p.id, "module": "packagechooser", "config": f"{p.id}.conf"}
                      for p in pages],
        "sequence": [{"show": show}, {"exec": list(EXEC)}, {"show": list(SHOW_FINISH)}],
    }
    settings.update(dict(_SETTINGS_FLAGS))
    return settings


def sequence_modules(settings: Mapping) -> List[str]:
    """Module names (instance suffix stripped) in sequence order."""
    out: List[str] = []
    for phase in settings["sequence"]:
        for entries in phase.values():
            out.extend(e.split("@", 1)[0] for e in entries)
    return out


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def render_settings_conf(settings: Mapping) -> str:
    lines = [_HEADER.rstrip("\n"), "---"]
    lines.append("modules-search: [ " + ", ".join(settings["modules-search"]) + " ]")
    lines.append("instances:")
    for inst in settings["instances"]:
        lines.append(f"- id: {inst['id']}")
        lines.append(f"  module: {inst['module']}")
        lines.append(f"  config: {inst['config']}")
    lines.append("sequence:")
    for phase in settings["sequence"]:
        for name, entries in phase.items():
            lines.append(f"- {name}:")
            for entry in entries:
                comment = _EXEC_COMMENTS.get(entry) if name == "exec" else None
                if comment:
                    lines.append(f"  # {comment}")
                lines.append(f"  - {entry}")
    for key, _ in _SETTINGS_FLAGS:
        lines.append(f"{key}: {_scalar(settings[key])}")
    return "\n".join(lines) + "\n"


def render_page_conf(page: Page) -> str:
    lines = [_HEADER.rstrip("\n"), "---", f"mode: {page.mode}",
             "# legacy: only globalstorage packagechooser_<id>; glueinstall reads it.",
             "method: legacy", "labels:", f"    step: {_scalar(page.step)}"]
    if page.default is not None:
        lines.append(f"default: {_scalar(page.default)}")
    lines.append("items:")
    for it in page.items:
        lines.append(f"    - id: {_scalar(it.id)}")
        lines.append(f"      name: {_scalar(it.name)}")
        lines.append(f"      description: {_scalar(it.description)}")
        lines.append(f"      screenshot: {_scalar(it.screenshot)}")
    return "\n".join(lines) + "\n"


def render_gallery(pages: List[Page]) -> str:
    """JSON map item id -> every screenshot path, for the gallery page."""
    gallery = {it.id: it.gallery for page in pages for it in page.items
               if it.id and it.gallery}
    return json.dumps(gallery, indent=2, ensure_ascii=False) + "\n"


def render_all(catalog) -> Dict[str, str]:
    """Relative path under packages/glue-calamares-config → file content."""
    files = {"settings.conf": render_settings_conf(build_settings(catalog))}
    pages = build_pages(catalog)
    for page in pages:
        files[f"modules/{page.id}.conf"] = render_page_conf(page)
    files["gluegallery.json"] = render_gallery(pages)
    return files


# ---------------------------------------------------------------------------
# fstab helper for the gluefstab job
# ---------------------------------------------------------------------------

def append_fstab_line(fstab_path: str, line: str) -> bool:
    """Append one fstab line unless an entry for the same fs_spec exists.
    Returns True when the file changed. Trailing newline guaranteed."""
    entry = " ".join(line.split())
    if not entry or "\n" in line.strip():
        raise ConfigError("fstab line must be a single non-empty line")
    spec = entry.split()[0]
    path = Path(fstab_path)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    for old in existing.splitlines():
        fields = old.split()
        if fields and not fields[0].startswith("#") and fields[0] == spec:
            return False
    if existing and not existing.endswith("\n"):
        existing += "\n"
    path.write_text(existing + entry + "\n", encoding="utf-8")
    return True


def main(argv=None) -> int:
    """Write the generated files into a glue-calamares-config checkout."""
    from glue_installer.catalog import load_catalog
    args = list(sys.argv[1:] if argv is None else argv)
    here = Path(__file__).resolve().parent.parent
    out = Path(args[0]) if args else here.parent / "glue-calamares-config"
    catalog = load_catalog(here / "catalog" / "catalog.json")
    for rel, text in render_all(catalog).items():
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        print(target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
