"""Calamares sequence + Glue selection pages (roadmap 10.3 lot 2, ADR-023).

Pure module: no libcalamares, no filesystem access except main(). Everything
under packages/glue-calamares-config that depends on the catalog is GENERATED
from here (settings.conf and modules/glue*.conf); tests assert the committed
files equal the output byte for byte. One owner per operation: Calamares owns
partition/mount/fstab/locale/keyboard/users/umount, glueinstall owns packages,
Glue configuration, services and Limine, gluefstab owns the swapfile line.

Every Glue page is QML (notesqml instances) and writes one globalstorage key,
`packagechooser_<page>` = comma-separated item ids (the shape the stock
packagechooser used); the desktop page writes SESSIONS_KEY (multi-select), so
selection_from_globalstorage() translates every key into the dict read by
calamares_adapter.parse_selection (no second catalog: ids come from it).
App store and Bluetooth are always installed (parse_selection defaults).
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Mapping, Optional

from glue_installer.calamares_gallery import (
    build_desktop_entries, render_data_js, render_qml_conf)


class ConfigError(ValueError):
    """A globalstorage page value is not something the catalog offers."""


GS_PREFIX = "packagechooser_"
# Screenshots as installed by the glue-installer PKGBUILD (catalog paths are
# relative to the catalog directory).
GAMING_ON = "gaming"
GAMING_OFF = "no-gaming"
# QML pages run as instances of the stock notesqml view module; the QML file
# is looked up in the branding directory (qmlSearch: branding)
NETWORK_STEP = "notesqml@gluenetwork"
DESKTOP_STEP = "notesqml@gluedesktop"
QML_PAGES = (("gluenetwork", "gluenetwork", "Network"),
             ("gluedesktop", "gluedesktop", "Desktop"))
# written by gluedesktop.qml: comma-separated session ids
SESSIONS_KEY = GS_PREFIX + "gluesessions"

# one-choice QML pages (ChoicePage.qml) in the order the user sees them
PAGE_IDS = ("gluekernel", "glueinit", "gluegaming")
SHOW_BEFORE = ("welcome", NETWORK_STEP, "locale", "keyboard", "partition", "users",
               DESKTOP_STEP)
SHOW_AFTER = ("summary",)
# Standard fstab is kept (it knows UUIDs, options, crypttab, btrfs subvolumes
# and runs after basestrap so the `filesystem` package cannot conflict with an
# earlier /etc/fstab); gluefstab adds only the Glue swapfile line right after.
EXEC = ("partition", "mount", "glueinstall", "fstab", "gluefstab", "locale",
        "keyboard", "localecfg", "users", "umount")
SHOW_FINISH = ("finished",)
# Never in the sequence: bootloader/initramfs are glue-boot's, services and the
# greeter are config_steps', packages come from basestrap in glueinstall.
FORBIDDEN_MODULES = frozenset({
    "bootloader", "grubcfg", "initcpio", "initcpiocfg", "dracut", "mkinitfs",
    "services-systemd", "services-openrc", "shellprocess", "contextualprocess",
    "pacstrap", "chwd", "unpackfs", "unpackfsc", "packages", "netinstall",
    "displaymanager", "plymouthcfg",
})
_EXEC_COMMENTS = {
    "glueinstall": "basestrap + Glue config + Limine over the mounted root (10.3)",
    "fstab": "after basestrap: the filesystem package ships /etc/fstab",
    "gluefstab": "appends the Glue swapfile line recorded by glueinstall",
    "locale": "locale/keyboard/users after glueinstall: glibc, kbd, shells, groups",
    "users": "needs the target's passwd/group (video, audio, …) and /bin/bash",
}
_SETTINGS_FLAGS = (
    ("branding", "glue"), ("prompt-install", True), ("dont-chroot", False),
    ("oem-setup", False), ("disable-cancel", False),
    ("disable-cancel-during-exec", True), ("hide-back-and-next-during-exec", True),
    ("quit-at-end", False),
)
_HEADER = ("# Generated by glue_installer.calamares_config from catalog.json;"
           " do not edit.\n# Regenerate: python -m glue_installer.calamares_config\n")


@dataclass
class Item:
    id: str
    name: str
    description: str
    badge: str = ""
    points: List[str] = field(default_factory=list)


@dataclass
class Page:
    id: str
    step: str
    mode: str                      # optional|required|optionalmultiple
    items: List[Item] = field(default_factory=list)
    default: Optional[str] = None  # pre-selected item id
    title: str = ""
    subtitle: str = ""

    @property
    def gs_key(self) -> str:
        return GS_PREFIX + self.id

    def item_ids(self) -> List[str]:
        return [it.id for it in self.items if it.id]


# ---------------------------------------------------------------------------
# Pages from the catalog
# ---------------------------------------------------------------------------

def default_session(catalog) -> str:
    return "gluewc" if any(s.id == "gluewc" for s in catalog.sessions) \
        else catalog.sessions[0].id


def build_pages(catalog) -> List[Page]:
    """The one-choice pages, ids and texts taken from the catalog only."""
    kernel = Page("gluekernel", "Kernel", "required",
                  title="Choose the kernel",
                  subtitle="The kernel is the core of the system. If you are not "
                           "sure, keep the recommended one.")
    for k in catalog.kernels:
        kernel.items.append(Item(k.id, k.name, k.description,
                                 badge="Recommended" if k.primary else ""))
    kernel.default = next((k.id for k in catalog.kernels if k.primary),
                          catalog.kernels[0].id)

    init = Page("glueinit", "Init system", "required",
                title="Choose the init system",
                subtitle="The init system starts your computer's services. All "
                         "three work the same for everyday use; keep the "
                         "recommended one if you are not sure.")
    for i in catalog.inits:
        init.items.append(Item(i.id, i.name, i.description,
                               badge="Recommended" if i.recommended else ""))
    init.default = next((i.id for i in catalog.inits if i.recommended),
                        catalog.inits[0].id)

    gaming = Page("gluegaming", "Gaming", "required",
                  title="Do you play games on this computer?",
                  subtitle="Gaming sets everything up in one go, so games work "
                           "right after the first login.")
    gaming.items.append(Item(
        GAMING_ON, "Yes, set it up for gaming",
        "Ready to play right after install, tuned like CachyOS.",
        badge="Larger download",
        points=["Steam with Proton, plus Heroic and Lutris for Epic, GOG and others",
                "Wine for Windows programs",
                "Graphics drivers for your card, installed automatically",
                "MangoHud, GameMode and Gamescope for FPS and smoother play",
                "A CPU scheduler and process priorities tuned for games"]))
    gaming.items.append(Item(
        GAMING_OFF, "No, keep it light",
        "A smaller, lighter system. You can still install Steam or other "
        "launchers later from Glue Apps."))
    gaming.default = GAMING_OFF
    pages = [kernel, init, gaming]
    assert tuple(p.id for p in pages) == PAGE_IDS
    return pages


def page_keys(catalog) -> List[str]:
    return [SESSIONS_KEY] + [p.gs_key for p in build_pages(catalog)]


def has_page_values(gs: Mapping) -> bool:
    """True when at least one Glue page wrote its globalstorage key."""
    return any(k.startswith(GS_PREFIX + "glue") and gs.get(k) is not None for k in gs)


def _picked(gs: Mapping, page: Page) -> Optional[List[str]]:
    raw = gs.get(page.gs_key)
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise ConfigError(f"{page.gs_key} must be a string, got {type(raw).__name__}")
    ids = [tok.strip() for tok in raw.split(",") if tok.strip()]
    unknown = sorted(set(ids) - set(page.item_ids()))
    if unknown:
        raise ConfigError(f"{page.gs_key}: unknown choice(s) {unknown}")
    if page.mode == "required" and len(ids) != 1:
        raise ConfigError(f"{page.gs_key}: exactly one choice required, got {ids}")
    if page.mode == "optional" and len(ids) > 1:
        raise ConfigError(f"{page.gs_key}: at most one choice allowed, got {ids}")
    return ids


def _sessions(gs: Mapping, catalog) -> Optional[List[str]]:
    raw = gs.get(SESSIONS_KEY)
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise ConfigError(f"{SESSIONS_KEY} must be a string, got {type(raw).__name__}")
    ids = [tok.strip() for tok in raw.split(",") if tok.strip()]
    unknown = sorted(set(ids) - {s.id for s in catalog.sessions})
    if unknown:
        raise ConfigError(f"{SESSIONS_KEY}: unknown choice(s) {unknown}")
    return list(dict.fromkeys(ids))


def selection_from_globalstorage(gs: Mapping, catalog) -> Dict[str, object]:
    """Translate the page keys into the parse_selection dict.
    Pages whose key is absent are left to parse_selection's defaults.
    Raises ConfigError (a ValueError) for ids outside the catalog."""
    pages = {p.id: p for p in build_pages(catalog)}
    sel: Dict[str, object] = {}
    sessions = _sessions(gs, catalog)
    if sessions is not None:
        sel["sessions"] = sessions
    for page_id, key in (("gluekernel", "kernel"), ("glueinit", "init")):
        ids = _picked(gs, pages[page_id])
        if ids:
            sel[key] = ids[0]
    gaming = _picked(gs, pages["gluegaming"])
    if gaming:
        sel["gaming"] = gaming[0] == GAMING_ON
    return sel


# ---------------------------------------------------------------------------
# settings.conf
# ---------------------------------------------------------------------------

def build_settings(catalog) -> Dict[str, object]:
    pages = build_pages(catalog)
    choosers = [f"notesqml@{p.id}" for p in pages]
    show = list(SHOW_BEFORE) + choosers + list(SHOW_AFTER)
    settings: Dict[str, object] = {
        # `local` = /usr/lib/calamares/modules (system); the Glue job modules
        # (glueinstall, gluefstab) live under /etc/calamares/modules.
        "modules-search": ["local", "/etc/calamares/modules"],
        "instances": [{"id": i, "module": "notesqml", "config": f"{i}.conf"}
                      for i, _, _ in QML_PAGES]
                     + [{"id": p.id, "module": "notesqml", "config": f"{p.id}.conf"}
                        for p in pages],
        "sequence": [{"show": show}, {"exec": list(EXEC)}, {"show": list(SHOW_FINISH)}],
    }
    settings.update(dict(_SETTINGS_FLAGS))
    return settings


def sequence_modules(settings: Mapping) -> List[str]:
    """Module names (instance suffix stripped) in sequence order."""
    out: List[str] = []
    for phase in settings["sequence"]:
        for entries in phase.values():
            out.extend(e.split("@", 1)[0] for e in entries)
    return out


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def render_settings_conf(settings: Mapping) -> str:
    lines = [_HEADER.rstrip("\n"), "---"]
    lines.append("modules-search: [ " + ", ".join(settings["modules-search"]) + " ]")
    lines.append("instances:")
    for inst in settings["instances"]:
        lines.append(f"- id: {inst['id']}")
        lines.append(f"  module: {inst['module']}")
        lines.append(f"  config: {inst['config']}")
    lines.append("sequence:")
    for phase in settings["sequence"]:
        for name, entries in phase.items():
            lines.append(f"- {name}:")
            for entry in entries:
                comment = _EXEC_COMMENTS.get(entry) if name == "exec" else None
                if comment:
                    lines.append(f"  # {comment}")
                lines.append(f"  - {entry}")
    for key, _ in _SETTINGS_FLAGS:
        lines.append(f"{key}: {_scalar(settings[key])}")
    return "\n".join(lines) + "\n"


def render_choice_js(pages: List[Page]) -> str:
    """ChoiceData.js for ChoicePage.qml: page id -> title, items, default."""
    data = {p.id: {"title": p.title, "subtitle": p.subtitle, "default": p.default,
                   "items": [{"id": it.id, "name": it.name, "description": it.description,
                              "badge": it.badge, "points": it.points} for it in p.items]}
            for p in pages}
    body = json.dumps(data, indent=2, ensure_ascii=False)
    return _HEADER.replace("#", "//") + ".pragma library\n\nvar pages = " + body + ";\n"


def render_all(catalog) -> Dict[str, str]:
    """Relative path under packages/glue-calamares-config → file content."""
    files = {"settings.conf": render_settings_conf(build_settings(catalog))}
    pages = build_pages(catalog)
    for page in pages:
        files[f"modules/{page.id}.conf"] = render_qml_conf(page.id, page.step)
    files["modules/gluechoice/ChoiceData.js"] = render_choice_js(pages)
    for inst, qml, label in QML_PAGES:
        files[f"modules/{inst}.conf"] = render_qml_conf(qml, label)
    files["modules/gluedesktop/DesktopData.js"] = render_data_js(
        build_desktop_entries(catalog, default_session(catalog)))
    return files


# ---------------------------------------------------------------------------
# fstab helper for the gluefstab job
# ---------------------------------------------------------------------------

def append_fstab_line(fstab_path: str, line: str) -> bool:
    """Append one fstab line unless an entry for the same fs_spec exists.
    Returns True when the file changed. Trailing newline guaranteed."""
    entry = " ".join(line.split())
    if not entry or "\n" in line.strip():
        raise ConfigError("fstab line must be a single non-empty line")
    spec = entry.split()[0]
    path = Path(fstab_path)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    for old in existing.splitlines():
        fields = old.split()
        if fields and not fields[0].startswith("#") and fields[0] == spec:
            return False
    if existing and not existing.endswith("\n"):
        existing += "\n"
    path.write_text(existing + entry + "\n", encoding="utf-8")
    return True


def main(argv=None) -> int:
    """Write the generated files into a glue-calamares-config checkout."""
    from glue_installer.catalog import load_catalog
    args = list(sys.argv[1:] if argv is None else argv)
    here = Path(__file__).resolve().parent.parent
    out = Path(args[0]) if args else here.parent / "glue-calamares-config"
    catalog = load_catalog(here / "catalog" / "catalog.json")
    for rel, text in render_all(catalog).items():
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        print(target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
