"""Desktop and network pages for Calamares (ADR-023).

Pure module. The QML pages (gluedesktop.qml, gluenetwork.qml) are static and
hand-written; only DesktopData.js and the notesqml instance configs are
generated from the catalog, via calamares_config.render_all(). Data is embedded
in a `.pragma library` script because Qt blocks XMLHttpRequest reads of local
files.
"""

from __future__ import annotations

import json
from typing import Dict, List

FILE_URL_PREFIX = "file://"
SCREENSHOT_ROOT = "/usr/share/glue-installer/catalog"
_HEADER_JS = ("// Generated by glue_installer.calamares_gallery from catalog.json;"
              " do not edit.\n// Regenerate: python -m glue_installer.calamares_config\n")
_HEADER_YAML = ("# Generated by glue_installer.calamares_gallery from catalog.json;"
                " do not edit.\n# Regenerate: python -m glue_installer.calamares_config\n")
DATA_PREFIX = ".pragma library\n\nvar entries = "
_WEIGHT = {5: "Very light", 4: "Light", 3: "Medium", 2: "Heavier", 1: "Heavy"}
_KIND = {"wm": "Tiling", "de": "Classic desktop"}


def build_desktop_entries(catalog, default_id: str) -> List[Dict[str, object]]:
    """One card per catalog session, in catalog order."""
    entries: List[Dict[str, object]] = []
    for s in catalog.sessions:
        shots = s.screenshots or ([s.screenshot] if s.screenshot else [])
        entries.append({
            "id": s.id, "name": s.name, "kind": _KIND.get(s.kind, s.kind),
            "description": s.description,
            "lightness": s.lightness, "weight": _WEIGHT.get(s.lightness, ""),
            "ease": s.ease, "ram": s.idle_ram or "",
            "wayland": s.session_type == "wayland",
            "images": [f"{FILE_URL_PREFIX}{SCREENSHOT_ROOT}/{p}" for p in shots],
            "checked": s.id == default_id,
        })
    return entries


def render_data_js(entries) -> str:
    body = json.dumps(list(entries), indent=2, ensure_ascii=False)
    return _HEADER_JS + DATA_PREFIX + body + ";\n"


def parse_data_js(text: str) -> List[Dict[str, object]]:
    """Inverse of render_data_js (used by tests)."""
    start = text.index(DATA_PREFIX) + len(DATA_PREFIX)
    return json.loads(text[start:].rstrip().rstrip(";"))


def render_qml_conf(filename: str, label: str) -> str:
    return (_HEADER_YAML + f"---\nqmlSearch: branding\nqmlFilename: {filename}\n"
            f"qmlLabel:\n    notes: {json.dumps(label)}\n")
