// Generated by glue_installer.calamares_config from catalog.json; do not edit.
// Regenerate: python -m glue_installer.calamares_config
.pragma library

var pages = {
  "gluekernel": {
    "title": "Choose the kernel",
    "subtitle": "The kernel is the core of the system. If you are not sure, keep the recommended one.",
    "default": "linux-cachyos",
    "items": [
      {
        "id": "linux-cachyos",
        "name": "CachyOS Kernel",
        "description": "The kernel tuned for speed, with the BORE scheduler and the CachyOS patches. The default for Glue Linux.",
        "badge": "Recommended",
        "points": []
      },
      {
        "id": "linux-zen",
        "name": "Zen Kernel",
        "description": "A community kernel tuned for a responsive desktop. A good second choice.",
        "badge": "",
        "points": []
      }
    ]
  },
  "glueinit": {
    "title": "Choose the init system",
    "subtitle": "The init system starts your computer's services. All three work the same for everyday use; keep the recommended one if you are not sure.",
    "default": "dinit",
    "items": [
      {
        "id": "dinit",
        "name": "dinit",
        "description": "Fast and simple, with quick boot times. The default for Glue Linux.",
        "badge": "Recommended",
        "points": []
      },
      {
        "id": "runit",
        "name": "runit",
        "description": "Small and proven over many years. Void Linux uses it.",
        "badge": "",
        "points": []
      },
      {
        "id": "openrc",
        "name": "OpenRC",
        "description": "Mature and well documented. Gentoo uses it.",
        "badge": "",
        "points": []
      }
    ]
  },
  "gluegaming": {
    "title": "Do you play games on this computer?",
    "subtitle": "Gaming sets everything up in one go, so games work right after the first login.",
    "default": "no-gaming",
    "items": [
      {
        "id": "gaming",
        "name": "Yes, set it up for gaming",
        "description": "Ready to play right after install, tuned like CachyOS.",
        "badge": "Larger download",
        "points": [
          "Steam with Proton, plus Heroic and Lutris for Epic, GOG and others",
          "Wine for Windows programs",
          "Graphics drivers for your card, installed automatically",
          "MangoHud, GameMode and Gamescope for FPS and smoother play",
          "A CPU scheduler and process priorities tuned for games"
        ]
      },
      {
        "id": "no-gaming",
        "name": "No, keep it light",
        "description": "A smaller, lighter system. You can still install Steam or other launchers later from Glue Apps.",
        "badge": "",
        "points": []
      }
    ]
  }
};
