// Generated by glue_installer.calamares_gallery from catalog.json; do not edit.
// Regenerate: python -m glue_installer.calamares_config
.pragma library

var entries = [
  {
    "id": "gluewc",
    "name": "gluewc + glueqs",
    "kind": "Tiling",
    "description": "Glue's own tiling desktop with the glueqs bar: windows arrange themselves, with smooth animations, three layouts (bsp, scroll, drift) on one key, a launcher, notifications and a settings panel. The default Glue session.",
    "lightness": 5,
    "weight": "Very light",
    "ease": 4,
    "ram": "about 450 MB",
    "wayland": true,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-glueqs-bar.png",
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-glueqs-overview.png"
    ],
    "checked": true
  },
  {
    "id": "gluewc-noctalia",
    "name": "gluewc + Noctalia",
    "kind": "Tiling",
    "description": "The same gluewc tiling desktop with the Noctalia shell instead of glueqs: a polished bar, a control center and widgets from the Noctalia project. A bit heavier than glueqs.",
    "lightness": 4,
    "weight": "Light",
    "ease": 4,
    "ram": "about 600 MB",
    "wayland": true,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-noctalia-bar.png",
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-noctalia-overview.png"
    ],
    "checked": false
  },
  {
    "id": "nvwm",
    "name": "nvwm",
    "kind": "Tiling",
    "description": "A tiny X11 tiling window manager with its own bar. The lightest choice here: keyboard-driven, for people who like to tweak.",
    "lightness": 5,
    "weight": "Very light",
    "ease": 3,
    "ram": "about 200 MB",
    "wayland": false,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/nvwm.png"
    ],
    "checked": false
  },
  {
    "id": "kde-plasma",
    "name": "KDE Plasma",
    "kind": "Classic desktop",
    "description": "A full classic desktop that works like Windows: taskbar, start menu, desktop icons and lots of settings. Best for beginners, and a good backup if tiling is not for you. The heaviest option.",
    "lightness": 2,
    "weight": "Heavier",
    "ease": 5,
    "ram": "about 1 GB",
    "wayland": false,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/kde-plasma.png"
    ],
    "checked": false
  },
  {
    "id": "xfce",
    "name": "XFCE",
    "kind": "Classic desktop",
    "description": "A light classic desktop with a panel, a menu, desktop icons and simple settings. Good for older or low-RAM computers.",
    "lightness": 3,
    "weight": "Medium",
    "ease": 5,
    "ram": "about 550 MB",
    "wayland": false,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/xfce.png"
    ],
    "checked": false
  },
  {
    "id": "gnome",
    "name": "GNOME (minimal)",
    "kind": "Classic desktop",
    "description": "A clean, modern desktop (minimal install): the Activities overview, a dock, Files and Settings, with no extra apps. Runs on Wayland and supports touchpad gestures.",
    "lightness": 2,
    "weight": "Heavier",
    "ease": 5,
    "ram": "about 1 GB",
    "wayland": true,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gnome.png"
    ],
    "checked": false
  },
  {
    "id": "cinnamon",
    "name": "Cinnamon",
    "kind": "Classic desktop",
    "description": "A classic desktop like Linux Mint's: start menu, panel and system tray. Familiar and friendly, medium weight.",
    "lightness": 3,
    "weight": "Medium",
    "ease": 5,
    "ram": "about 750 MB",
    "wayland": false,
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/cinnamon.png"
    ],
    "checked": false
  }
];
