// Generated by glue_installer.calamares_gallery from catalog.json; do not edit.
// Regenerate: python -m glue_installer.calamares_config
.pragma library

var entries = [
  {
    "id": "gluewc",
    "name": "gluewc",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-glueqs-bar.png"
    ]
  },
  {
    "id": "nvwm",
    "name": "nvwm",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/nvwm.png"
    ]
  },
  {
    "id": "kde-plasma",
    "name": "KDE Plasma",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/kde-plasma.png"
    ]
  },
  {
    "id": "xfce",
    "name": "XFCE",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/xfce.png"
    ]
  },
  {
    "id": "gnome",
    "name": "GNOME (minimal)",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gnome.png"
    ]
  },
  {
    "id": "cinnamon",
    "name": "Cinnamon",
    "kind": "session",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/cinnamon.png"
    ]
  },
  {
    "id": "glueqs",
    "name": "glueqs",
    "kind": "shell",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-glueqs-bar.png",
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-glueqs-overview.png"
    ]
  },
  {
    "id": "noctalia",
    "name": "Noctalia Shell",
    "kind": "shell",
    "images": [
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-noctalia-bar.png",
      "file:///usr/share/glue-installer/catalog/screenshots/gluewc-noctalia-overview.png"
    ]
  }
];
