---
efi:
    mountPoint: "/boot"
    recommendedSize: 512MiB
    minimumSize: 300MiB
    label: "EFI"
# no `file`: the Glue swapfile (sized from RAM) is created by glueinstall,
# so Calamares' fstab module never makes a second /swapfile
userSwapChoices: [ none, small ]
initialSwapChoice: small
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
