---
efi:
    mountPoint: "/boot"
    recommendedSize: 512MiB
    minimumSize: 300MiB
    label: "EFI"
userSwapChoices: [ none, small, file ]
initialSwapChoice: small
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
