---
defaultGroups: [ users, wheel, audio, video, input, network, storage ]
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: true
passwordRequirements:
    minLength: 1
user:
  shell: /bin/bash
  forbidden_names: [ root ]
hostname:
  location: EtcFile
  template: "glue"
